-- test_v082.sql
-- pg_regress regression tests for pgmnemo v0.8.2
--
-- Coverage:
--   T1: F1 — traverse_temporal_window honors include_unverified='true' (not just 'on')
--   T2: F1 — traverse_temporal_window honors include_unverified='on'
--   T3: F1 — traverse_temporal_window excludes ghosts when include_unverified='off'
--   T4: F2 — recall_lessons returns 0 rows when all lessons are ghosts (default gate)
--   T5: F2 — NOTICE is emitted by recall_lessons when ghost lessons exist and 0 rows returned
--   T6: F2 — recall_lessons returns ghost lessons when include_unverified='on'
--   T7: F2 — recall_hybrid returns 0 rows and emits NOTICE when only ghost lessons exist
--   T8: F2 — recall_hybrid returns ghost lessons when include_unverified='on'
--
-- Prerequisites: pgmnemo 0.8.2 installed.
-- NOTE: pg_regress expected output must be regenerated by operator after first run.
--       Operator: make installcheck 2>&1 | head -40 to capture expected/actual diff.

SET pgmnemo.gate_strict = 'off';
SET pgmnemo.include_unverified = 'off';
SET client_min_messages = 'notice';

-- =============================================================================
-- Setup: insert test data for v0.8.2 tests
-- =============================================================================
-- role='tc_v082' for easy cleanup
-- Ghost lessons: no commit_sha, no artifact_hash → verified_at IS NULL
-- We need one "anchor" lesson for traverse_temporal_window (start_id)

-- Anchor lesson (with provenance → verified, will always be visible)
INSERT INTO pgmnemo.agent_lesson (
    role, topic, lesson_text, embedding, commit_sha, artifact_hash, verified_at
) VALUES (
    'tc_v082', 'anchor',
    'Anchor lesson for traverse_temporal_window tests.',
    ('[' || repeat('0.04000,', 1023) || '0.04000]')::vector(1024),
    'abc123def456', 'sha256:aabbcc', NOW()
);

-- Ghost lesson A: near the anchor in time (will be found by traverse if include_unverified ON)
INSERT INTO pgmnemo.agent_lesson (
    role, topic, lesson_text, embedding
) VALUES (
    'tc_v082', 'ghost_a',
    'Ghost lesson A for v0.8.2 F1 test — no provenance.',
    ('[' || repeat('0.03900,', 1023) || '0.03900]')::vector(1024)
);

-- Ghost lesson B: for recall F2 test (role='tc_v082_ghost')
INSERT INTO pgmnemo.agent_lesson (
    role, topic, lesson_text, embedding
) VALUES (
    'tc_v082_ghost', 'ghost_recall',
    'Ghost lesson for recall F2 notice test — unverified.',
    ('[' || repeat('0.05000,', 1023) || '0.05000]')::vector(1024)
);

-- =============================================================================
-- T1: F1 — traverse_temporal_window honors include_unverified='true'
-- Expect: ghost_a is found when include_unverified='true' (was broken before 0.8.2)
-- =============================================================================

SET pgmnemo.include_unverified = 'true';

SELECT COUNT(*) > 0 AS t1_traverse_honors_true
FROM pgmnemo.traverse_temporal_window(
    (SELECT id FROM pgmnemo.agent_lesson WHERE role='tc_v082' AND topic='anchor' LIMIT 1),
    INTERVAL '1 hour',
    TRUE,    -- include_unlinked
    'tc_v082',
    NULL,
    20
);

-- =============================================================================
-- T2: F1 — traverse_temporal_window honors include_unverified='on'
-- =============================================================================

SET pgmnemo.include_unverified = 'on';

SELECT COUNT(*) > 0 AS t2_traverse_honors_on
FROM pgmnemo.traverse_temporal_window(
    (SELECT id FROM pgmnemo.agent_lesson WHERE role='tc_v082' AND topic='anchor' LIMIT 1),
    INTERVAL '1 hour',
    TRUE,
    'tc_v082',
    NULL,
    20
);

-- =============================================================================
-- T3: F1 — traverse_temporal_window excludes ghosts when include_unverified='off'
-- =============================================================================

SET pgmnemo.include_unverified = 'off';

SELECT COUNT(*) = 0 AS t3_traverse_excludes_ghosts_when_off
FROM pgmnemo.traverse_temporal_window(
    (SELECT id FROM pgmnemo.agent_lesson WHERE role='tc_v082' AND topic='anchor' LIMIT 1),
    INTERVAL '1 hour',
    TRUE,
    'tc_v082',
    NULL,
    20
);

-- =============================================================================
-- T4: F2 — recall_lessons returns 0 rows when all in-scope lessons are ghosts
-- (include_unverified='off', role='tc_v082_ghost' has only unverified lessons)
-- =============================================================================

SET pgmnemo.include_unverified = 'off';

SELECT COUNT(*) = 0 AS t4_recall_zero_rows_for_ghost_scope
FROM pgmnemo.recall_lessons(
    ('[' || repeat('0.05000,', 1023) || '0.05000]')::vector(1024),
    5,
    'tc_v082_ghost',
    NULL,
    NULL
);

-- =============================================================================
-- T5: F2 — NOTICE is emitted when 0 rows returned and ghost lessons exist
-- The NOTICE text appears in pg_regress output; operator regenerates expected.
-- Verified by: the query above (T4) should have produced a NOTICE line.
-- Here we confirm that ghost lessons DO exist in scope (prerequisite for notice).
-- =============================================================================

SELECT COUNT(*) >= 1 AS t5_ghost_lessons_exist_in_scope
FROM pgmnemo.agent_lesson
WHERE role = 'tc_v082_ghost'
  AND is_active
  AND t_valid_to = 'infinity'::TIMESTAMPTZ
  AND verified_at IS NULL;

-- =============================================================================
-- T6: F2 — recall_lessons returns ghost lessons when include_unverified='on'
-- =============================================================================

SET pgmnemo.include_unverified = 'on';

SELECT COUNT(*) >= 1 AS t6_recall_returns_ghosts_when_flag_on
FROM pgmnemo.recall_lessons(
    ('[' || repeat('0.05000,', 1023) || '0.05000]')::vector(1024),
    5,
    'tc_v082_ghost',
    NULL,
    NULL
);

-- =============================================================================
-- T7: F2 — recall_hybrid returns 0 rows and NOTICE when only ghost lessons exist
-- (include_unverified='off'; text-only path avoids needing a query embedding)
-- =============================================================================

SET pgmnemo.include_unverified = 'off';

SELECT COUNT(*) = 0 AS t7_hybrid_zero_rows_for_ghost_scope
FROM pgmnemo.recall_hybrid(
    ('[' || repeat('0.05000,', 1023) || '0.05000]')::vector(1024),
    'ghost lesson recall notice test',
    5,
    'tc_v082_ghost',
    NULL
);

-- =============================================================================
-- T8: F2 — recall_hybrid returns ghost lessons when include_unverified='on'
-- =============================================================================

SET pgmnemo.include_unverified = 'on';

SELECT COUNT(*) >= 1 AS t8_hybrid_returns_ghosts_when_flag_on
FROM pgmnemo.recall_hybrid(
    ('[' || repeat('0.05000,', 1023) || '0.05000]')::vector(1024),
    'ghost lesson recall notice test',
    5,
    'tc_v082_ghost',
    NULL
);

-- =============================================================================
-- Cleanup
-- =============================================================================

DELETE FROM pgmnemo.agent_lesson WHERE role IN ('tc_v082', 'tc_v082_ghost');

-- Restore defaults
SET pgmnemo.include_unverified = 'off';
SET pgmnemo.gate_strict = 'enforce';
